# Generated by Django 5.2.14 on 2026-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('scad_source', models.TextField()),
                ('preview', models.ImageField(blank=True, upload_to='png/')),
                ('mesh', models.FileField(blank=True, upload_to='stl/')),
                ('error', models.TextField(blank=True)),
                ('generator', models.CharField(default='heuristic', max_length=32)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
