# Generated by Django 5.2.14 on 2026-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='brief',
            field=models.TextField(blank=True, help_text='engineering brief from phase 1'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='stage_log',
            field=models.TextField(blank=True, help_text='timestamped progress messages'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('planning', 'planning'), ('generating', 'generating'), ('rendering', 'rendering'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='generator',
            field=models.CharField(default='heuristic', max_length=64),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='scad_source',
            field=models.TextField(blank=True),
        ),
    ]
