# Generated by Django 5.2.14 on 2026-05-28 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0002_sketch_brief_sketch_stage_log_sketch_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='if set, this sketch is a revision of the parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='sketches.sketch'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='revision_request',
            field=models.TextField(blank=True, help_text='natural-language change request applied to the parent'),
        ),
    ]
