# Generated by Django 5.2.14 on 2026-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0003_sketch_parent_sketch_revision_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='category',
            field=models.CharField(blank=True, help_text='furniture | structure | foliage | mechanical | …', max_length=40),
        ),
        migrations.AddField(
            model_name='sketch',
            name='interface_json',
            field=models.JSONField(blank=True, default=dict, help_text='params, anchors, modules — the component contract'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='kind',
            field=models.CharField(choices=[('component', 'component'), ('assembly', 'assembly')], default='component', max_length=16),
        ),
        migrations.AddField(
            model_name='sketch',
            name='module_name',
            field=models.CharField(blank=True, help_text='top-level OpenSCAD module name (the composer entry point)', max_length=80),
        ),
        migrations.AddField(
            model_name='sketch',
            name='tags',
            field=models.CharField(blank=True, help_text='comma-separated search tags', max_length=200),
        ),
    ]
