# Generated by Django 5.2.14 on 2026-05-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0005_componentref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentref',
            name='anchor_to_json',
            field=models.JSONField(blank=True, default=dict, help_text='Anchor placement: {parent_slot, anchor_name}'),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='component_revision',
            field=models.IntegerField(default=0, help_text='Pin to a specific revision if needed'),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='instance_name',
            field=models.CharField(blank=True, help_text='Instance label for this placement', max_length=64),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in assembly'),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='params_json',
            field=models.JSONField(blank=True, default=dict, help_text='Parameter overrides for this instance'),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='rotate',
            field=models.JSONField(blank=True, default=list, help_text='[x, y, z] rotation (deg)'),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='scale',
            field=models.JSONField(blank=True, default=list, help_text='[x, y, z] scale factors'),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='translate',
            field=models.JSONField(blank=True, default=list, help_text='[x, y, z] translation'),
        ),
    ]
