# Generated by Django 5.2.14 on 2026-05-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0006_alter_componentref_anchor_to_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentref',
            name='anchor_to_json',
        ),
        migrations.RemoveField(
            model_name='componentref',
            name='component_revision',
        ),
        migrations.RemoveField(
            model_name='componentref',
            name='scale',
        ),
        migrations.AlterField(
            model_name='componentref',
            name='instance_name',
            field=models.CharField(blank=True, help_text='Label for this placement (defaults to module_name)', max_length=64),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='params_json',
            field=models.JSONField(blank=True, default=dict, help_text='Parameter overrides, e.g. {"height": 1200}'),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='rotate',
            field=models.JSONField(blank=True, default=list, help_text='[x, y, z] Euler rotation in degrees'),
        ),
        migrations.AlterField(
            model_name='componentref',
            name='translate',
            field=models.JSONField(blank=True, default=list, help_text='[x, y, z] translation in mm'),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('pending', 'pending'), ('planning', 'planning'), ('generating', 'generating'), ('rendering', 'rendering'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16),
        ),
    ]
