# Generated by Django 5.2.14 on 2026-05-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0009_bridgestandard_standardchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(help_text="Stable slug, e.g. 'deck_width_min'", max_length=60, unique=True)),
                ('parameter', models.CharField(help_text="SCAD variable name to extract, e.g. 'deck_width'", max_length=80)),
                ('comparator', models.CharField(choices=[('min', '≥ threshold_min'), ('max', '≤ threshold_max'), ('range', 'threshold_min ≤ value ≤ threshold_max')], max_length=8)),
                ('threshold_min', models.FloatField(blank=True, help_text='Lower bound (mm or unitless)', null=True)),
                ('threshold_max', models.FloatField(blank=True, help_text='Upper bound (mm or unitless)', null=True)),
                ('bridge_types', models.JSONField(blank=True, default=list, help_text="[] = all bridge types; or ['suspension', 'arch', …]")),
                ('element_types', models.JSONField(blank=True, default=list, help_text="[] = all elements; or ['deck', 'pylon', 'cable', …]")),
                ('severity', models.CharField(choices=[('warn', 'warning'), ('fail', 'fail')], default='fail', max_length=8)),
                ('quote', models.TextField(blank=True, help_text='Verbatim text from the standard that backs this rule')),
                ('description', models.CharField(blank=True, help_text='Human-readable rule description', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='sketches.bridgestandard')),
            ],
            options={
                'ordering': ('rule_id',),
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_score', models.FloatField(default=0.0, help_text='0–100 percent compliance')),
                ('passed', models.IntegerField(default=0)),
                ('warned', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('element_type', models.CharField(blank=True, help_text='Auto-detected structural element: deck, pylon, cable, arch, truss, abutment, …', max_length=40)),
                ('results_json', models.JSONField(default=list, help_text='List of {rule_id, parameter, status, value, threshold, message}')),
                ('rag_notes', models.TextField(blank=True, help_text='LLM-generated standards compliance commentary')),
                ('auto_repair_prompt', models.TextField(blank=True, help_text='Targeted repair prompt if failed rules exist')),
                ('sketch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='sketches.sketch')),
            ],
            options={
                'ordering': ('-ran_at',),
            },
        ),
    ]
